# flake8: noqa

"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


__version__ = "0.1.1"

# import ApiClient
from deutschland.dip_bundestag.api_client import ApiClient

# import Configuration
from deutschland.dip_bundestag.configuration import Configuration

# import exceptions
from deutschland.dip_bundestag.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)
