"""
Deutscher Bundestag - DIP

API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

The version of the OpenAPI document: 1.2
Contact: parlamentsdokumentation@bundestag.de
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.dip_bundestag.model.vorgang import Vorgang

from deutschland import dip_bundestag

globals()["Vorgang"] = Vorgang
from deutschland.dip_bundestag.model.vorgang_list_response_all_of import (
    VorgangListResponseAllOf,
)


class TestVorgangListResponseAllOf(unittest.TestCase):
    """VorgangListResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVorgangListResponseAllOf(self):
        """Test VorgangListResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VorgangListResponseAllOf()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
