"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.drucksache import Drucksache

from deutschland import dip_bundestag

globals()["Drucksache"] = Drucksache
from deutschland.dip_bundestag.model.drucksache_list_response_all_of import (
    DrucksacheListResponseAllOf,
)


class TestDrucksacheListResponseAllOf(unittest.TestCase):
    """DrucksacheListResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDrucksacheListResponseAllOf(self):
        """Test DrucksacheListResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DrucksacheListResponseAllOf()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
