"""
Deutscher Bundestag - DIP

API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

The version of the OpenAPI document: 1.2
Contact: parlamentsdokumentation@bundestag.de
Generated by: https://openapi-generator.tech
"""

import unittest

from deutschland.dip_bundestag.api.vorgangspositionen_api import (  # noqa: E501
    VorgangspositionenApi,
)

from deutschland import dip_bundestag


class TestVorgangspositionenApi(unittest.TestCase):
    """VorgangspositionenApi unit test stubs"""

    def setUp(self):
        self.api = VorgangspositionenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_vorgangsposition(self):
        """Test case for get_vorgangsposition

        Liefert Metadaten zu einer Vorgangsposition  # noqa: E501
        """
        pass

    def test_get_vorgangsposition_list(self):
        """Test case for get_vorgangsposition_list

        Liefert eine Liste von Metadaten zu Vorgangspositionen  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
