"""
Deutscher Bundestag - DIP

API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

The version of the OpenAPI document: 1.2
Contact: parlamentsdokumentation@bundestag.de
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.dip_bundestag.model.get_vorgang404_response import (
    GetVorgang404Response,
)

from deutschland import dip_bundestag


class TestGetVorgang404Response(unittest.TestCase):
    """GetVorgang404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetVorgang404Response(self):
        """Test GetVorgang404Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetVorgang404Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
