"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.vorgangsposition import Vorgangsposition

from deutschland import dip_bundestag

globals()["Vorgangsposition"] = Vorgangsposition
from deutschland.dip_bundestag.model.vorgangsposition_list_response_all_of import (
    VorgangspositionListResponseAllOf,
)


class TestVorgangspositionListResponseAllOf(unittest.TestCase):
    """VorgangspositionListResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVorgangspositionListResponseAllOf(self):
        """Test VorgangspositionListResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VorgangspositionListResponseAllOf()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
