"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.bundesland import Bundesland

from deutschland import dip_bundestag


class TestBundesland(unittest.TestCase):
    """Bundesland unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBundesland(self):
        """Test Bundesland"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Bundesland()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
