"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.drucksache_autoren_anzeige_inner import (
    DrucksacheAutorenAnzeigeInner,
)

from deutschland import dip_bundestag


class TestDrucksacheAutorenAnzeigeInner(unittest.TestCase):
    """DrucksacheAutorenAnzeigeInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDrucksacheAutorenAnzeigeInner(self):
        """Test DrucksacheAutorenAnzeigeInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DrucksacheAutorenAnzeigeInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
