"""
Deutscher Bundestag - DIP

API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

The version of the OpenAPI document: 1.2
Contact: parlamentsdokumentation@bundestag.de
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.dip_bundestag.model.vorgangsbezug import Vorgangsbezug
from deutschland.dip_bundestag.model.vorgangspositionbezug_all_of import (
    VorgangspositionbezugAllOf,
)

from deutschland import dip_bundestag

globals()["Vorgangsbezug"] = Vorgangsbezug
globals()["VorgangspositionbezugAllOf"] = VorgangspositionbezugAllOf
from deutschland.dip_bundestag.model.vorgangspositionbezug import Vorgangspositionbezug


class TestVorgangspositionbezug(unittest.TestCase):
    """Vorgangspositionbezug unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVorgangspositionbezug(self):
        """Test Vorgangspositionbezug"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Vorgangspositionbezug()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
