"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.list_response_base import ListResponseBase
from deutschland.dip_bundestag.model.plenarprotokoll import Plenarprotokoll
from deutschland.dip_bundestag.model.plenarprotokoll_list_response_all_of import (
    PlenarprotokollListResponseAllOf,
)

from deutschland import dip_bundestag

globals()["ListResponseBase"] = ListResponseBase
globals()["Plenarprotokoll"] = Plenarprotokoll
globals()["PlenarprotokollListResponseAllOf"] = PlenarprotokollListResponseAllOf
from deutschland.dip_bundestag.model.plenarprotokoll_list_response import (
    PlenarprotokollListResponse,
)


class TestPlenarprotokollListResponse(unittest.TestCase):
    """PlenarprotokollListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlenarprotokollListResponse(self):
        """Test PlenarprotokollListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlenarprotokollListResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
