"""
Deutscher Bundestag - DIP

API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

The version of the OpenAPI document: 1.2
Contact: parlamentsdokumentation@bundestag.de
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.dip_bundestag.model.vorgang_verlinkung import VorgangVerlinkung

from deutschland import dip_bundestag


class TestVorgangVerlinkung(unittest.TestCase):
    """VorgangVerlinkung unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVorgangVerlinkung(self):
        """Test VorgangVerlinkung"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VorgangVerlinkung()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
