"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.quadrant import Quadrant
from deutschland.dip_bundestag.model.zuordnung import Zuordnung

from deutschland import dip_bundestag

globals()["Quadrant"] = Quadrant
globals()["Zuordnung"] = Zuordnung
from deutschland.dip_bundestag.model.fundstelle import Fundstelle


class TestFundstelle(unittest.TestCase):
    """Fundstelle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFundstelle(self):
        """Test Fundstelle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Fundstelle()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
