"""
    DIP Bundestag API

    Bundestag: Dokumentations- und Informationssystem für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.dip_bundestag.api.plenarprotokoll_api import (  # noqa: E501
    PlenarprotokollApi,
)

from deutschland import dip_bundestag


class TestPlenarprotokollApi(unittest.TestCase):
    """PlenarprotokollApi unit test stubs"""

    def setUp(self):
        self.api = PlenarprotokollApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_plenarprotokoll(self):
        """Test case for plenarprotokoll

        Liste aller Plenarprotokolle  # noqa: E501
        """
        pass

    def test_plenarprotokoll_id(self):
        """Test case for plenarprotokoll_id

        Metadaten zu Plenarprotokoll  # noqa: E501
        """
        pass

    def test_plenarprotokoll_text(self):
        """Test case for plenarprotokoll_text

        Liste aller Volltexte der Plenarprotokolle  # noqa: E501
        """
        pass

    def test_plenarprotokoll_text_id_get(self):
        """Test case for plenarprotokoll_text_id_get

        Volltexte der Plenarprotokolle  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
