"""
Deutscher Bundestag - DIP

API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

The version of the OpenAPI document: 1.2
Contact: parlamentsdokumentation@bundestag.de
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.dip_bundestag.model.ueberweisung import Ueberweisung

from deutschland import dip_bundestag


class TestUeberweisung(unittest.TestCase):
    """Ueberweisung unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUeberweisung(self):
        """Test Ueberweisung"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Ueberweisung()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
