"""
    DIP Bundestag API

    Bundestag: Dokumentations- und Informationssystem für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.dip_bundestag.api.person_api import PersonApi  # noqa: E501

from deutschland import dip_bundestag


class TestPersonApi(unittest.TestCase):
    """PersonApi unit test stubs"""

    def setUp(self):
        self.api = PersonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_person(self):
        """Test case for person

        Liste aller Personenstammdaten  # noqa: E501
        """
        pass

    def test_person_id(self):
        """Test case for person_id

        Personenstammdaten  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
