"""
    DIP Bundestag API

    Bundestag: Dokumentations- und Informationssystem für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.dip_bundestag.api.vorgang_api import VorgangApi  # noqa: E501

from deutschland import dip_bundestag


class TestVorgangApi(unittest.TestCase):
    """VorgangApi unit test stubs"""

    def setUp(self):
        self.api = VorgangApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_vorgang(self):
        """Test case for vorgang

        Liste aller Vorgänge  # noqa: E501
        """
        pass

    def test_vorgang_id(self):
        """Test case for vorgang_id

        Metadaten zu Vorgang  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
