"""
Deutscher Bundestag - DIP

API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

The version of the OpenAPI document: 1.2
Contact: parlamentsdokumentation@bundestag.de
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.dip_bundestag.model.aktivitaet_anzeige import AktivitaetAnzeige

from deutschland import dip_bundestag


class TestAktivitaetAnzeige(unittest.TestCase):
    """AktivitaetAnzeige unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAktivitaetAnzeige(self):
        """Test AktivitaetAnzeige"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AktivitaetAnzeige()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
