"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.drucksache_text import DrucksacheText

from deutschland import dip_bundestag

globals()["DrucksacheText"] = DrucksacheText
from deutschland.dip_bundestag.model.drucksache_text_list_response_all_of import (
    DrucksacheTextListResponseAllOf,
)


class TestDrucksacheTextListResponseAllOf(unittest.TestCase):
    """DrucksacheTextListResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDrucksacheTextListResponseAllOf(self):
        """Test DrucksacheTextListResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DrucksacheTextListResponseAllOf()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
