"""
    DIP Bundestag API

    Bundestag: Dokumentations- und Informationssystem für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.dip_bundestag.api.vorgangsposition_api import (  # noqa: E501
    VorgangspositionApi,
)

from deutschland import dip_bundestag


class TestVorgangspositionApi(unittest.TestCase):
    """VorgangspositionApi unit test stubs"""

    def setUp(self):
        self.api = VorgangspositionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_vorgangsposition(self):
        """Test case for vorgangsposition

        Liste aller Vorgangspositionen  # noqa: E501
        """
        pass

    def test_vorgangsposition_id(self):
        """Test case for vorgangsposition_id

        Metadaten zu Vorgangsposition  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
