"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.list_response_base import ListResponseBase
from deutschland.dip_bundestag.model.vorgangsposition import Vorgangsposition
from deutschland.dip_bundestag.model.vorgangsposition_list_response_all_of import (
    VorgangspositionListResponseAllOf,
)

from deutschland import dip_bundestag

globals()["ListResponseBase"] = ListResponseBase
globals()["Vorgangsposition"] = Vorgangsposition
globals()["VorgangspositionListResponseAllOf"] = VorgangspositionListResponseAllOf
from deutschland.dip_bundestag.model.vorgangsposition_list_response import (
    VorgangspositionListResponse,
)


class TestVorgangspositionListResponse(unittest.TestCase):
    """VorgangspositionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVorgangspositionListResponse(self):
        """Test VorgangspositionListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VorgangspositionListResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
