"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.get_vorgang_list401_response import (
    GetVorgangList401Response,
)

from deutschland import dip_bundestag


class TestGetVorgangList401Response(unittest.TestCase):
    """GetVorgangList401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetVorgangList401Response(self):
        """Test GetVorgangList401Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetVorgangList401Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
