"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.urheber import Urheber

from deutschland import dip_bundestag


class TestUrheber(unittest.TestCase):
    """Urheber unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUrheber(self):
        """Test Urheber"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Urheber()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
