"""
Deutscher Bundestag - DIP

API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

The version of the OpenAPI document: 1.2
Contact: parlamentsdokumentation@bundestag.de
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.dip_bundestag.model.list_response_base import ListResponseBase
from deutschland.dip_bundestag.model.person import Person
from deutschland.dip_bundestag.model.person_list_response_all_of import (
    PersonListResponseAllOf,
)

from deutschland import dip_bundestag

globals()["ListResponseBase"] = ListResponseBase
globals()["Person"] = Person
globals()["PersonListResponseAllOf"] = PersonListResponseAllOf
from deutschland.dip_bundestag.model.person_list_response import PersonListResponse


class TestPersonListResponse(unittest.TestCase):
    """PersonListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonListResponse(self):
        """Test PersonListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PersonListResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
