"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.dip_bundestag.api.aktivitten_api import AktivittenApi  # noqa: E501

from deutschland import dip_bundestag


class TestAktivittenApi(unittest.TestCase):
    """AktivittenApi unit test stubs"""

    def setUp(self):
        self.api = AktivittenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_aktivitaet(self):
        """Test case for get_aktivitaet

        Liefert Metadaten zu einer Aktivität  # noqa: E501
        """
        pass

    def test_get_aktivitaet_list(self):
        """Test case for get_aktivitaet_list

        Liefert eine Liste von Metadaten zu Aktivitäten  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
