"""
Deutscher Bundestag - DIP

API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

The version of the OpenAPI document: 1.2
Contact: parlamentsdokumentation@bundestag.de
Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.dip_bundestag.model.plenarprotokoll_text import PlenarprotokollText

from deutschland import dip_bundestag

globals()["PlenarprotokollText"] = PlenarprotokollText
from deutschland.dip_bundestag.model.plenarprotokoll_text_list_response_all_of import (
    PlenarprotokollTextListResponseAllOf,
)


class TestPlenarprotokollTextListResponseAllOf(unittest.TestCase):
    """PlenarprotokollTextListResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlenarprotokollTextListResponseAllOf(self):
        """Test PlenarprotokollTextListResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlenarprotokollTextListResponseAllOf()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
