"""
    DIP Bundestag API

    Bundestag: Dokumentations- und Informationssystem für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.dip_bundestag.api.drucksache_api import DrucksacheApi  # noqa: E501

from deutschland import dip_bundestag


class TestDrucksacheApi(unittest.TestCase):
    """DrucksacheApi unit test stubs"""

    def setUp(self):
        self.api = DrucksacheApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_drucksache(self):
        """Test case for drucksache

        Liste aller Drucksachen  # noqa: E501
        """
        pass

    def test_drucksache_id(self):
        """Test case for drucksache_id

        Metadaten zu Drucksache  # noqa: E501
        """
        pass

    def test_drucksache_text(self):
        """Test case for drucksache_text

        Liste aller Volltexte der Drucksachen  # noqa: E501
        """
        pass

    def test_drucksache_text_id(self):
        """Test case for drucksache_text_id

        Volltexte einer Drucksache  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
