"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.dip_bundestag.api.plenarprotokolle_api import (  # noqa: E501
    PlenarprotokolleApi,
)

from deutschland import dip_bundestag


class TestPlenarprotokolleApi(unittest.TestCase):
    """PlenarprotokolleApi unit test stubs"""

    def setUp(self):
        self.api = PlenarprotokolleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_plenarprotokoll(self):
        """Test case for get_plenarprotokoll

        Liefert Metadaten zu einem Plenarprotokoll  # noqa: E501
        """
        pass

    def test_get_plenarprotokoll_list(self):
        """Test case for get_plenarprotokoll_list

        Liefert eine Liste von Metadaten zu Plenarprotokollen  # noqa: E501
        """
        pass

    def test_get_plenarprotokoll_text(self):
        """Test case for get_plenarprotokoll_text

        Liefert Volltext und Metadaten zu einem Plenarprotokoll  # noqa: E501
        """
        pass

    def test_get_plenarprotokoll_text_list(self):
        """Test case for get_plenarprotokoll_text_list

        Liefert eine Liste von Volltexten und Metadaten zu Plenarprotokollen  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
