"""
    Deutscher Bundestag - DIP

    API des Dokumentations- und Informationssystems für Parlamentsmaterialien  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: parlamentsdokumentation@bundestag.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dip_bundestag.model.fundstelle import Fundstelle
from deutschland.dip_bundestag.model.vorgangsbezug import Vorgangsbezug
from deutschland.dip_bundestag.model.zuordnung import Zuordnung

from deutschland import dip_bundestag

globals()["Fundstelle"] = Fundstelle
globals()["Vorgangsbezug"] = Vorgangsbezug
globals()["Zuordnung"] = Zuordnung
from deutschland.dip_bundestag.model.plenarprotokoll import Plenarprotokoll


class TestPlenarprotokoll(unittest.TestCase):
    """Plenarprotokoll unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlenarprotokoll(self):
        """Test Plenarprotokoll"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Plenarprotokoll()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
