"""
    Bundestag: Dokumentations- und Informationssystem für Parlamentsmaterialien

    DIP Bundestag API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.dip_bundestag.api.default_api import DefaultApi  # noqa: E501

from deutschland import dip_bundestag


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_aktivitaet_get(self):
        """Test case for aktivitaet_get

        Liste aller Aktivitäten  # noqa: E501
        """
        pass

    def test_aktivitaet_id_get(self):
        """Test case for aktivitaet_id_get

        Metadaten zu Aktivitäten  # noqa: E501
        """
        pass

    def test_drucksache_get(self):
        """Test case for drucksache_get

        Liste aller Drucksachen  # noqa: E501
        """
        pass

    def test_drucksache_id_get(self):
        """Test case for drucksache_id_get

        Metadaten zu Drucksachen  # noqa: E501
        """
        pass

    def test_drucksache_text_get(self):
        """Test case for drucksache_text_get

        Liste aller Volltexte der Drucksachen  # noqa: E501
        """
        pass

    def test_drucksache_text_id_get(self):
        """Test case for drucksache_text_id_get

        Soweit vorhanden werden zusätzlich die Volltexte der Drucksachen ausgegeben  # noqa: E501
        """
        pass

    def test_person_get(self):
        """Test case for person_get

        Liste aller Personenstammdaten  # noqa: E501
        """
        pass

    def test_person_id_get(self):
        """Test case for person_id_get

        Personenstammdaten  # noqa: E501
        """
        pass

    def test_plenarprotokoll_get(self):
        """Test case for plenarprotokoll_get

        Liste aller Plenarprotokolle  # noqa: E501
        """
        pass

    def test_plenarprotokoll_id_get(self):
        """Test case for plenarprotokoll_id_get

        Metadaten zu Plenarprotokollen  # noqa: E501
        """
        pass

    def test_plenarprotokoll_text_get(self):
        """Test case for plenarprotokoll_text_get

        Liste aller Volltexte der Plenarprotokolle  # noqa: E501
        """
        pass

    def test_plenarprotokoll_text_id_get(self):
        """Test case for plenarprotokoll_text_id_get

        Soweit vorhanden werden zusätzlich die Volltexte der Plenarprotokolle ausgegeben  # noqa: E501
        """
        pass

    def test_vorgang_get(self):
        """Test case for vorgang_get

        Liste aller Vorgänge  # noqa: E501
        """
        pass

    def test_vorgang_id_get(self):
        """Test case for vorgang_id_get

        Metadaten zu Vorgängen  # noqa: E501
        """
        pass

    def test_vorgangsposition_get(self):
        """Test case for vorgangsposition_get

        Liste aller Vorgangspositionen  # noqa: E501
        """
        pass

    def test_vorgangsposition_id_get(self):
        """Test case for vorgangsposition_id_get

        Metadaten zu Vorgangspositionen  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
